default: &DEFAULT
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *DEFAULT
  database: dingr_development

production:
  <<: *DEFAULT
  database: dingr_development

test:
  <<: *DEFAULT
  database: dingr_test


